### ISSUE TITLE
Project does not contain license information

### ISSUE THREAD

**Issue by m-wichmann** [attie/linker-generated-array#2]
I was planning on using lga in a commercial project, but this project does not contain any license information. Could you add a license to your code, so I know if I can use this?

**Comment by attie** [comment]
Absolutely! I'm going to have to give this some thought though - as it's something that you build into your application I don't think LGPL would be suitable, which I've used in the past... I want to properly understand the implications of the licence before I make a choice.

**Comment by attie** [comment]
As of 8ff3580 this project is licensed using the MIT license. I hope that this is acceptable for your purposes.

Attie

**Comment by m-wichmann** [comment]
Thanks, that's perfect.
